
storage:
  image: busybox
  volumes:
      - /var/lib/postgresql/data
db:
  image: mysql:5.7.17
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  volumes_from:
    - storage
  ports:
    - "3306:3306"
